### ISSUE TITLE
Image actions not work

### ISSUE THREAD

**Issue by ArkadiuszMichalski** [eight04/jn-npp-emmet#10]
Option 'Update Image Size' works in NPP? I try with some absolute and relative path but without any result. Even when I put image file in the same folder where my html file and use <img src="test.gif" alt=""> nothing happend. The same is for "Encode\Decode data:URL image".

The same problem like before https://github.com/eight04/jn-npp-emmet/issues/1#issuecomment-188645179 , after fix was fine but now see once again update image size or encode/decode not work. Looks like it's Emmet fault, not new jN version.

I don't know what old version I used (some from 2016), but in this version all this command works fine.
0.2.0 (Feb 26, 2016)  << here you fix this bug.

**Comment by eight04** [comment]
It would be nice if you can put the problem in this thread not just link it.

**Comment by ArkadiuszMichalski** [comment]
Ok, I edit first comment and put full infos.

**Comment by eight04** [comment]
Emmet had [changed its interface](https://github.com/emmetio/emmet/pull/456) in v1.6.0. I ignored it because I can't read Russian. All features related to file reader was broken since jn-npp-emmet v1.1.0. I'll fix it later.

**Comment by eight04** [comment]
Try https://github.com/eight04/jn-npp-emmet/pull/12

**Comment by ArkadiuszMichalski** [comment]
Works fine.
