### ISSUE TITLE
Add some infos to main project file

### ISSUE THREAD

**Issue by ArkadiuszMichalski** [eight04/jn-npp-emmet#11]
Can you add to plugins\jN\includes\emmet.js some comments at the begining with jn-npp-emmet version, emmet version, jN version, author, project adress and other usefull info? This can be help full for opening new bugs.

**Comment by eight04** [comment]
Including the version number in `dist` folder sounds like a good idea. Users usually just delete the zip file after copying everything into notepad++ folder, it's hard to tell which release those files are copied from. Ideally, it should be integrated into the building process.

BTW, I'm thinking whether we should move `dialog`, `FileStream` into `emmet` subfolder, so there is only one subfolder inside `dist` and it's clear that the `includes/emmet` folder is used by `includes/emmet.js`.

**Comment by ArkadiuszMichalski** [comment]
Yep, all additional folders/files should sit only in one folder `includes/emmet`, we will have better order beetwen other JN scripts.
