### ISSUE TITLE
Less depending on the other files

### ISSUE THREAD

**Issue by ArkadiuszMichalski** [eight04/jn-npp-emmet#6]
This `require("includes/MenuCmds.js");` is really needs? Only one times used `MenuCmds.EDIT_INS_TAB();` but we must have this file in includes folder (its came from jN plugin, not yours, plus xxx scripts which are usually removes or disables). You should inform what files are neccessary in your install guide.

**Comment by eight04** [comment]
I prefer to use module provided by jN.

:+1: for adding the dependencies in readme.

**Comment by ArkadiuszMichalski** [comment]
Sure, modules from jN are useful, but they should be place in some other folder than `includes` (not mixed with all other autoloaded scripts that add own menu to NPP because we instinctively move all these scripts if we do not need them). Something like was done for `.js` files in `lib` folder.

But true is that you don't need use `require("includes/MenuCmds.js");` because this files was loaded automatically if they exist in includes folder. Before we can run any Emmet action (what use MenuCmds global object) we always get access to this object.

But it's still unnecessary dependence, just remove `require("includes/MenuCmds.js");` and instead `MenuCmds.EDIT_INS_TAB();` use `Editor.runMenuCmd(42008)` and nobody needs remember that `MenuCmds.js` must be in `includes` folder.
