### ISSUE TITLE
Last jN 2.2.185.2 and Wrap With Abbreviation generate error

### ISSUE THREAD

**Issue by ArkadiuszMichalski** [eight04/jn-npp-emmet#8]
After update jN to last version I get error when second time invoke  `Wrap With Abbreviation`, first time works correct (show dialog box) but next time always throw.
Error info:
`'handle.document' jest pusty lub nie jest obiektem
line: 128, pos: 7`
It came from `jN\includes\emmet.js`.
When I back to previous jN 2.1.181 version (from 2016) problem not exist.

Platform detial:
Windows7 64-bit
Notepad++ 7.5.5 32-bit
jN 2.2.185.2
jN-npp-emmet 1.1.2

**Comment by ArkadiuszMichalski** [comment]
Strange, the same story what we see in past:
https://github.com/eight04/jn-npp-emmet/issues/1#issuecomment-189073792
but this fix not work with last jN version.

**Comment by eight04** [comment]
I can reproduce it with jN_2.2.185.2_x86.
![image](https://user-images.githubusercontent.com/1324510/37141765-11e2b08a-22f1-11e8-905f-04b57c7cde7e.png)

**Comment by ArkadiuszMichalski** [comment]
@eight04 Any idea what is going wrong? Looks like dialog is destroy (instead close) and once again `entry` is `null`. Should I open bug for jN repo?

**Comment by eight04** [comment]
I'm not sure, I didn't remember what the old API looks like. Anyway, could you try [this branch](https://github.com/eight04/jn-npp-emmet/pull/9)?

**Comment by ArkadiuszMichalski** [comment]
This fix works fine, thx.
